spring:
  mail:
    properties:
      mail:
        debug: 'true'
        smtp:
          starttls:
            enable: 'true'
            required: 'true'
          auth: 'true'
        mime:
          charset: UTF-8
        transport:
          protocol: smtp
    host: smtp.gmail.com
    username: najwoo0318
    password: vnfr fmfa yveb wcxs
    port: '587'
    default-encoding: "UTF-8\t"
